all: CrossRoad.cpp CrossRoad.h ferry.cpp ferry.h helper.c helper.h main.cpp monitor.h narrowBridge.cpp narrowBridge.h parser.cpp parser.h WriteOutput.c WriteOutput.h
	g++ -Wall -pthread -o simulator CrossRoad.cpp CrossRoad.h ferry.cpp ferry.h helper.c helper.h main.cpp monitor.h narrowBridge.cpp narrowBridge.h parser.cpp parser.h WriteOutput.c WriteOutput.h -I.
